;each line must be padded to 16 bytes
.db "SONIC   ECLIPSE "
.db "FIRST   DEMO    "
.db "                "
.db "PROJECT LEADER  "
.db "        MR,CAT  "
.db "                "
.db "ARTWORK MR,CAT  "
.db "                "
.db "MAIN PRGMR,CAT  "
.db "PRG     YOSHISTR"
.db "                "
.db "LEVELS  MR,CAT  "
.db "LEVELS  YOSHISTR"
.db "                "
.db "MUSIC   VADAPEGA"
.db "                "
.db "SFX     MR,CAT  "
.db "                "
.db "TEST    AY JAY  "
.db "TEST    LILAC   "
.db "TEST    NARCOLGR"
.db "                "
.db "ORG GAMESEGA    "
.db "ORG GAMEASPECT  "
.db "                "
.db "DISASM  GLITCH  "
.db "TOOLS   GLITCH  "
.db "THANKS  FOR     "
.db "PLAYING         "
.db "                "
